config/routes.rb
Mutsuki::Application.routes.draw do

  get "home/index"
  root to: 'home#index'
  devise_for :admins, :path => '', :path_names => {:sign_in => 'signin', :sign_out => 'signout'}

  resources :users
  resources :events
  resources :authorized_apps

  mount API => "/api"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :rememberable, :trackable, :validatable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
end

app/models/authorized_app.rb
class AuthorizedApp < ActiveRecord::Base
  validates :name, :key,
    presence: true,
    uniqueness: true
  validates :key, 
    length: { is: 16 },
    format: { with: /\A[\w]+\z/ }
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events

  validates :name, :date, :creator_user_id,
    presence: true

  validates :private_flg, 
    inclusion: {in: [true, false]}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_events, dependent: :destroy
  has_many :events, through: :user_events

  before_validation :check_whitespace, :only => [:os]

  private
  def check_whitespace
    self.os = 'Other' if self.os.blank?
  end
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :user_id,
    :uniqueness => {:scope =>:event_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authorized_apps_controller.rb
class AuthorizedAppsController < ApplicationController
  before_action :set_authorized_app, only: [:show, :edit, :update, :destroy]

  # GET /authorized_apps
  # GET /authorized_apps.json
  def index
    @authorized_apps = AuthorizedApp.page(params[:page])
  end

  # GET /authorized_apps/1
  # GET /authorized_apps/1.json
  def show
  end

  # GET /authorized_apps/new
  def new
    @authorized_app = AuthorizedApp.new
  end

  # GET /authorized_apps/1/edit
  def edit
  end

  # POST /authorized_apps
  # POST /authorized_apps.json
  def create
    @authorized_app = AuthorizedApp.new(authorized_app_params)

    respond_to do |format|
      if @authorized_app.save
        format.html { redirect_to @authorized_app, notice: 'Authorized app was successfully created.' }
        format.json { render action: 'show', status: :created, location: @authorized_app }
      else
        format.html { render action: 'new' }
        format.json { render json: @authorized_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorized_apps/1
  # PATCH/PUT /authorized_apps/1.json
  def update
    respond_to do |format|
      if @authorized_app.update(update_authorized_app_params)
        format.html { redirect_to @authorized_app, notice: 'Authorized app was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @authorized_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorized_apps/1
  # DELETE /authorized_apps/1.json
  def destroy
    @authorized_app.destroy
    respond_to do |format|
      format.html { redirect_to authorized_apps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorized_app
      @authorized_app = AuthorizedApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authorized_app_params
      params['authorized_app']['key'] = SecureRandom.hex(8)
      params.require(:authorized_app).permit(:name, :key)
    end

    def update_authorized_app_params
      params.require(:authorized_app).permit(:name, :key)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.page(params[:page])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params['event']['creator_user_id'] = 0 if action_name == "create"
      params.require(:event).permit(:name, :date, :private_flg, :creator_user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!  

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:os)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorized_apps_helper.rb
module AuthorizedAppsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authorized_apps/_form.html.erb
<%= form_for(@authorized_app) do |f| %>
  <% if @authorized_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorized_app.errors.count, "error") %> prohibited this authorized_app from being saved:</h2>

      <ul>
      <% @authorized_app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Register App', data: {confirm: 'Are you sure ?', disable_with: 'Waiting...'}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/authorized_apps/edit.html.erb
<h1>Editing Authorized App</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorized_app %> |
<%= link_to 'Back to List', authorized_apps_path %>

app/views/authorized_apps/index.html.erb
<h1>Listing Authorized Apps</h1>

<table  class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Key</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authorized_apps.each do |authorized_app| %>
      <tr>
        <td><%= authorized_app.id %></td>
        <td><%= authorized_app.name %></td>
        <td><%= authorized_app.key %></td>
        <td><%= link_to 'Show', authorized_app %></td>
        <td><%= link_to 'Edit', edit_authorized_app_path(authorized_app) %></td>
        <td><%= link_to 'Destroy', authorized_app, method: :delete, data: { confirm: 'Are you sure ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate(@authorized_apps) %>

<br>

<%= button_to 'Register New App', new_authorized_app_path, method: :get, class: 'btn btn-primary' %>

app/views/authorized_apps/new.html.erb
<h1>New Authorized App</h1>

<%= render 'form' %>

<%= link_to 'Back to List', authorized_apps_path %>

app/views/authorized_apps/show.html.erb
<h1>Detail of <%= @authorized_app.name %></h1>

<table  class="table table-hover">
    <tr>
      <th>Id : </th>
      <td><%= @authorized_app.id %></td>
    </tr>
    <tr>
      <th>Name : </th>
      <td><%= @authorized_app.name %></td>
    </tr>
    <tr>
      <th>Key : </th>
      <td><%= @authorized_app.key %></td>
    </tr>
</table>

<%= link_to 'Edit', edit_authorized_app_path(@authorized_app) %> |
<%= link_to 'Back to List', authorized_apps_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, 
      use_two_digit_numbers: true,
      date_separator: ' - '
    %>
  </div>
  <div class="field">
    <label>Private Event ?</label> 
    <label class="radio inline"><%= f.radio_button :private_flg, 'true', checked: true %>Yes</label>
    <label class="radio inline"><%= f.radio_button :private_flg, 'false' %>No</label>
  </div><br>
  <div class="actions">
    <%= f.submit 'Register Event', data: {confirm: 'Are you sure ?', disable_with: 'Waiting...'}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back to List', events_path %>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<table  class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Date</th>
      <th>Private</th>
      <th>CreatorId</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
	<td><%= event.private_flg? ? 'Yes' : 'No' %></td>
        <td><%= event.creator_user_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate(@events) %>

<br>

<%= button_to 'Create New Event', new_event_path, method: :get, class: 'btn btn-primary' %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back to List', events_path %>

app/views/events/show.html.erb
<h1>Detail of <%= @event.name %></h1>

<table  class="table table-hover">
    <tr>
      <th>Name : </th>
      <td><%= @event.name %></td>
    </tr>
    <tr>
      <th>Date : </th>
      <td><%= @event.date %></td>
    </tr>
    <tr>
      <th>Private : </th>
      <td><%= @event.private_flg? ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>CreatorId : </th>
      <td><%= @event.creator_user_id %></td>
    </tr>
</table>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back to List', events_path %>

app/views/home/index.html.erb
<h1>Mutsuki Admin Home</h1>
<p>This is the data management tool</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Mutsuki Admin", root_path, id: "logo" %>
      <% if admin_signed_in? %>
        <ul class="nav pull-right">
	  <li><%= link_to current_admin.email, '#' %></li>
	  <li><%= link_to "Sign out", destroy_admin_session_path, method: :delete %></li>
        </ul>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_left_navi.html.erb
<% if admin_signed_in? %>
  <nav>
    <ul class="nav nav-list span2">
      <li class="nav-header">Menu</li>
      <li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to "Home", root_path %></li>
      <li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to "User", users_path %></li>
      <li class="<%= 'active' if params[:controller] == 'events' %>"><%= link_to "Event", events_path %></li>
      <li class="<%= 'active' if params[:controller] == 'authorized_apps' %>"><%= link_to "Authorized Apps", authorized_apps_path %></li>
    </ul>
  </nav>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mutsuki</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="span12">
        <% if notice %>
          <p class="alert"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="span3">
        <%= render 'layouts/left_navi' %>
      </div>
      <div class="span9">
        <% if admin_signed_in? or params[:controller] == 'devise/sessions' %>
          <%= yield %>
        <% end %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>OS</label>
    <%= f.text_field :os %>
  </div>
  <div class="actions">
    <%= f.submit 'Register User', data: {confirm: 'Are you sure ?', disable_with: 'Waiting...'}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back to List', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table  class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th># of Events</th>
      <th>OS</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.events.length %></td>
	<td><%= user.os.blank? ? '-' : user.os %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate(@users) %>

<br>

<%= button_to 'Create New User', new_user_path, method: :get, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back to List', users_path %>

app/views/users/show.html.erb
<h1>Detail of User-<%= @user.id %></h1>

<table  class="table table-hover">
    <tr>
      <th>Id : </th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th>OS : </th>
      <td><%= @user.os.blank? ? '-' : @user.os%></td>
    </tr>
    <tr>
      <th>EventIds : </th>
      <% if @user.events.blank? %>
        <td>-</td>
      <% else %>
        <td>
          <% @user.events.each do |event| %>
	    <%= link_to event.id, event %>
          <% end %>
        </td>
      <% end %>
    </tr>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back to Lsit', users_path %>